sudo: required

services:
  - docker

language: go

go:
  - 1.8.x

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
    - REPO=sillenttroll/go_feed_service

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker build --force-rm -t $REPO . ;
    docker tag $REPO $REPO:$COMMIT;
    docker push $REPO;
    fi
